version: "3.8"

services:
  api:
    image: apirnc
    container_name: apirnc
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.apirnc.rule=Host(`rnc.ypw.com.do`)"
      - "traefik.http.routers.apirnc.entrypoints=websecure"
      - "traefik.http.routers.apirnc.tls=true"
      - "traefik.http.routers.apirnc.tls.certresolver=le"
      - "traefik.http.services.apirnc.loadbalancer.server.port=5147"
    networks:
      - traefik-net

networks:
  traefik-net:
    external: true
